version: "3.8"

services:
  backend:
    image: btxrd-backend
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    ports:
      - "8000:8000"
    volumes:
      - /data:/data
    env_file:
      - .env.jetson
    mem_limit: 3500m
    restart: unless-stopped

  frontend:
    build:
      context: ./btxrd-frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    restart: unless-stopped
    depends_on:
      - backend

networks:
  default:
    driver: bridge
